# Generated by Django 6.0.3 on 2026-03-17 09:18

import applications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(upload_to=applications.models.resume_upload_path),
        ),
    ]
