# Generated by Django 6.0.3 on 2026-03-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_deadline_alter_job_skills_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='deadline',
            field=models.DateField(blank=True, help_text='Application deadline', null=True),
        ),
    ]
